version: '3'

services:
  app:
    build: .
    container_name: ai-restaurant-review-generator
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - OPENAI_API_KEY=sk-your-actual-api-key-here
      - OPENAI_BASE_URL=https://api.openai.com/v1
      - OPENAI_MODEL=gpt-3.5-turbo
    # env_file:
    #  - .env
    restart: unless-stopped
