version: '3'

services:
  app:
    build: .
    container_name: ai-restaurant-review-generator
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_BASE_URL=${OPENAI_BASE_URL}
    env_file:
      - .env
    restart: unless-stopped
